ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Переменные окружения
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libxkbcommon0 \
    libxcb1 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../requirements.txt .

ARG INSTALL_TORCH=1

# Установка Python зависимостей
RUN if [ "${INSTALL_TORCH}" = "0" ]; then \
        grep -vE '^(torch|torchvision)[=<>]' requirements.txt > /tmp/req.txt && \
        pip3 install --no-cache-dir --no-deps --ignore-installed -r /tmp/req.txt; \
    else \
        pip3 install --no-cache-dir -r requirements.txt; \
    fi

COPY ../. .

EXPOSE 8000

CMD ["uvicorn", "fire_uav.api.main_rest:app", "--host", "0.0.0.0", "--port", "8000"]