ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-opencv \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    libgstreamer1.0-0 \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ../requirements.txt .

RUN grep -vE '^(torch|torchvision|PyYAML|Pygments|opencv-python)[=<>]' requirements.txt > /tmp/req.txt && \
    pip3 install --upgrade-strategy only-if-needed --no-deps -r /tmp/req.txt

COPY ../. .

CMD ["python3", "-m", "fire_uav.main"]