version: '3.8'

services:
  client:
#    depends_on:
#     - telemetry
    image: revchenkov/bpla_fire_smoke_human:latest
    build:
      context: ../
      dockerfile: containerization/Dockerfile_jetson
      args:
        BASE_IMAGE: nvcr.io/nvidia/pytorch:26.02-py3-igpu
    runtime: nvidia
    network_mode: host
    ipc: host
    environment:
      FIRE_UAV_ROLE: module
      FIRE_UAV_PROFILE: jetson
      FIRE_UAV_SETTINGS: /app/fire_uav/config/settings_jetson.json
    volumes:
       - /dev:/dev
       - /tmp/argus_socket:/tmp/argus_socket
       - /tmp/.X11-unix:/tmp/.X11-unix
       - /home/user/compvis/BPLA_Docker/BPLA_fire_smoke_human-in-the-forest:/app/
    privileged: true

  telemetry:
    image: revchenkov/telemetry:latest
    build:
      context: ../
      dockerfile: containerization/telemetry/Dockerfile
    network_mode: host
    environment:
      CONFIG_PATH: /app/telemetry/telemetry_config.json
      HOST: 0.0.0.0
      PORT: 8000
#    devices:
#      - /dev/ttyUSB2:/dev/ttyUSB2
#      - /dev/ttyTHS1:/dev/ttyTHS1
    group_add:
      - dialout
    restart: unless-stopped