version: '3.8'

services:
  client:
    image: revchenkov/bpla_fire_smoke_human_rk3588:latest
    build:
      context: ../
      dockerfile: containerization/Dockerfile_rk3588
      args:
        BASE_IMAGE: python:3.10-slim
        INSTALL_TORCH: "1"

    platform: linux/arm64
    network_mode: host
    ipc: host
    privileged: true

    environment:
      FIRE_UAV_ROLE: module
      FIRE_UAV_PROFILE: rk3588
      FIRE_UAV_SETTINGS: /app/fire_uav/config/settings_jetson.json
      LD_LIBRARY_PATH: /usr/lib

    devices:
      - /dev/video0:/dev/video0
      - /dev/rknpu:/dev/rknpu
      - /dev/dri:/dev/dri

    volumes:
      - /usr/lib/librknnrt.so:/usr/lib/librknnrt.so
      - /dev:/dev

    restart: unless-stopped

  telemetry:
    image: revchenkov/telemetry:latest
    build:
      context: ../
      dockerfile: containerization/telemetry/Dockerfile
    network_mode: host
    environment:
      CONFIG_PATH: /app/telemetry/telemetry_config.json
    devices:
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyTHS1:/dev/ttyTHS1
    group_add:
      - dialout
    restart: unless-stopped



    